//
//  XNOptionSwitch.h
//  FinancialManager
//
//  Created by xnkj on 15/9/25.
//  Copyright © 2015年 xiaoniu. All rights reserved.
//

#ifndef XNNotificationTagDefine
#define XNNotificationTagDefine

//登入通知
#define XNUSERLOGINNOTIFICATION @"XNUSERLOGINNOTIFICATION"

//启动切换到主界面通知
#define XNUSERENTERMAININTERFACE @"XNUSERENTERMAININTERFACE"

//登入成功
#define XN_USER_LOGIN_SUCCESS_NOTIFICATINO @"XNUSERLOGINSUCCESSNOTIFICATION"

//退出
#define XN_USER_EXIT_SUCCESS_NOTIFICATION @"XN_USER_EXIT_SUCCESS_NOTIFICATION"

//切换tab键通知
#define XN_USER_SWITCH_TAB_HOMEPAGE @"XN_USER_SWITCH_TAB_HOMEPAGE"
#define XN_USER_SWITCH_TAB_FINANCIALMANAGER @"XN_USER_SWITCH_TAB_FINANCIALMANAGER"
#define XN_USER_SWITCH_TAB_LIECAI @"XN_USER_SWITCH_TAB_LIECAI"
#define XN_USER_SWITCH_TAB_CUSTOMERSERVICE @"XN_USER_SWITCH_TAB_CUSTOMERSERVICE"
#define XN_USER_SWITCH_TAB_MYINFO @"XN_USER_SWITCH_TAB_MYINFO"

//通知设置手势密码
#define XN_USER_LOGIN_SET_GESTURE_NOTIFICATION @"XNUSERLOGINSERGESTURENOTIFICATION"

//网络环境切换
#define UINetworkChangedNotification                    @"UINetworkChangedNotification"

//绑卡成功
#define XNUSERBINDCARDSUCCESSNOTIFICATION     @"XNUSERBINDCARDSUCCESSNOTIFICATION"

//产品之间跳转
#define XNUSERPRODUCTLISTSWITCH @"XNUSERPRODUCTLISTSWITCH"

//环信账号和密码为空
#define XNUSERHXNILNOTIFICATION @"XNUSERHXNILNOTIFICATION"

//远程推送通知，用于页面跳转
#define XN_REMOTE_NOTIFICATION @"XNRemoteNotification"

//阅读广告结束
#define XN_READ_AD_FINISHED @"XN_READ_AD_FINISHED"

//加载最新的消息未读数
#define XN_MESSAGECENTER_UNREAD_MESSAGE_COUNT @"XN_MESSAGECENTER_UNREAD_MESSAGE_COUNT"

//通知消息数目的变化
#define XN_READ_MESSAGE_CHANGE @"XN_READ_MESSAGE_CHANGE"

//红包发放成功
#define XN_RED_PACKET_DISPATCH_SUCCESS @"XN_RED_PACKET_DISPATCH_SUCCESS"

//未读消息数
#define XN_UNREAD_MESSAGE_COUNT @"XN_UNREAD_MESSAGE_COUNT"

//移动客服未读消息
#define XN_UNREAD_SERVICE_MSG @"XN_UNREAD_SERVICE_MSG"
//更改联系客服显示未读图标
#define XN_UNREAD_SERVICE_ICON @"XN_UNREAD_SERVICE_ICON"

//更新交易动态上tab的数目变化
#define XN_TRADE_READ_MESSAGE_COUNT @"XN_TRADE_READ_MESSAGE_COUNT"

//显示手势密码的通知
#define XN_SHOW_GESTURE_PASSWORD_NOTIFICTION @"XN_SHOW_GESTURE_PASSWORD_NOTIFICTION"

//显示指纹密码的通知
#define XN_SHOW_FINGER_PASSWORD_NOTIFICATION @"XN_SHOW_FINGER_PASSWORD_NOTIFICATION"

//更新token
#define XN_UPDATE_TOKEN_NOTIFICATION @"XN_UPDATE_TOKEN_NOTIFICATION"

//app从后台进入前台
#define XN_APP_FROM_BACK_TO_FRONT @"app_fron_back_to_front"

//app从前台进入后台
#define XN_APP_FROM_FRONT_TO_BACK @"app_from_front_to_back"

//是否存在猎财未读信息
#define XN_APP_UNREAD_REDDOT_NOTIFICATION @"XN_APP_UNREAD_REMINDDOT_NOTIFICATION"

//是否有未完成的新手任务
#define XN_APP_NEW_USER_TASK_NOTIFICATION @"XN_APP_NEW_USER_TASK_NOTIFICATION"

//启动完成通知
#define XN_APP_LAUNCH_SUCCESS_NOTIICATION @"XN_APP_LAUNCH_SUCCESS_NOTIICATION"

//通知消息免打扰
#define XN_USER_MESSAGE_DISTUBTED @"XN_USER_MESSAGE_DISTUBTED"

//首页-消息未读数
#define XN_HOME_UNREAD_MESSAGE_COUNT @"XN_HOME_UNREAD_MESSAGE_COUNT"

//更新投资记录中未读标志
#define XN_INVEST_RECORD_UNREAD_COUNT @"XN_INVEST_RECORD_UNREAD_COUNT"

//投资-基金列表,展示默认类型数据
#define XN_DEFAULT_TYPE_FUND_LIST_NOTIFICATION @"XN_DEFAULT_TYPE_FUND_LIST_NOTIFICATION"

//理财师列表下载完毕通知（对于子线程的处理)
#define XN_CFG_LIST_FINISHED_NOTIFICATION @"XN_CFG_LIST_FINISHED_NOTIFICATION"



#define Sign_Share_Succeed @"Sign_Share_Succeed"








#endif
