//
//  XNWithDrawBankCardInfoMode.m
//  FinancialManager
//
//  Created by xnkj on 15/10/22.
//  Copyright © 2015年 xiaoniu. All rights reserved.
//

#import "XNWithDrawBankCardInfoMode.h"

@implementation XNWithDrawBankCardInfoMode

+ (instancetype )initWithDrawBankCardWithObject:(NSDictionary *)params
{
    if ([NSObject isValidateObj:params]) {
        
        XNWithDrawBankCardInfoMode * pd = [[XNWithDrawBankCardInfoMode alloc]init];
        
        pd.bankCode = [[params objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USERCARDDATA] objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USERCARDDATA_BANKCODE];
        pd.bankName = [[params objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USERCARDDATA] objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USERCARDDATA_BANKNAME];
        pd.buyerUid = [[params objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USERCARDDATA] objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USERCARDDATA_BUYERUID];
        pd.buyerUin = [[params objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USERCARDDATA] objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USERCARDDATA_BUYERUIN];
        pd.userIdentity = [[params objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USERCARDDATA] objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USERCARDDATA_IDENTIFYCARD];
        pd.partnerId = [[params objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USERCARDDATA] objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USERCARDDATA_PARTNER_ID];
        pd.provider = [[params objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USERCARDDATA] objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USERCARDDATA_PROVIDER];
        pd.providerPartnerNo = [[params objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USERCARDDATA] objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USERCARDDATA_PROVIDER_PARTNER_NO];
        pd.userCardRemark = [[params objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USERCARDDATA] objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USERCARDDATA_REMARK];
        pd.userCardStatus = [[params objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USERCARDDATA] objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USERCARDDATA_STATUS];
        pd.userCardNumber = [[params objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USERCARDDATA] objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USERCARDDATA_USER_CARD_NO];
        pd.userId = [[params objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USERCARDDATA] objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USERCARDDATA_USER_ID];
        pd.userName = [[params objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USERCARDDATA] objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USERCARDDATA_USER_NAME];
        pd.userPhoneNumber = [[params objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USERCARDDATA] objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USERCARDDATA_USER_PHONE_NO];
        pd.isNeedBranch = [params objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_IS_NEEDBRANCH];
        pd.fee = [NSString stringWithFormat:@"%@",[[params objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USEROUTFEE] objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USEROUTFEE_FEE]];
        pd.hasFee = [[params objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USEROUTFEE] objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USEROUTFEE_HASFEE];
        pd.limitTime = [[params objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USEROUTFEE] objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_USEROUTFEE_LIMITTIMES];
        pd.bankCodeAttach = [[params objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_BANKCODEDATA] objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_BANKCODEDATA_ATTACH];
        pd.dayLimitAmount = [[params objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_BANKCODEDATA] objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_BANKCODEDATA_DAYLIMITAMOUNT];
        pd.monthLimitAmount = [[params objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_BANKCODEDATA] objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_BANKCODEDATA_MONTHLIMITAMOUNT];
        pd.providerBankCode = [[params objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_BANKCODEDATA] objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_BANKCODEDATA_PROVIDER_BANK_CODE];
        pd.providerName = [[params objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_BANKCODEDATA] objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_BANKCODEDATA_PROVIDER_NAME];
        pd.recordLimitAmount = [[params objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_BANKCODEDATA] objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_BANKCODEDATA_RECORD_LIMIT_AMOUNT];
        pd.bankCodeRemark = [[params objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_BANKCODEDATA] objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_BANKCODEDATA_REMARK];
        pd.servicePhone = [[params objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_BANKCODEDATA] objectForKey:XN_ACCOUNT_MYACCONT_WITHDRAW_BANKCARD_BANKCODEDATA_SERVICE_PHONE];
        
        return pd;
    }
    return nil;
}

@end
